@echo off
echo [[94mSTART[0m] Preparing WinPork command center...
echo [[96mPERFORM[0m] Move current dir to C:\...
cd C:\
echo [[96mPERFORM[0m] Size window with parms [cols=230 lines=64]...
mode con: cols=230 lines=64
echo [[96mPERFORM[0m] Rewrite prompt to string [WINPORK $P$$]...
prompt WINPORK $P$$
echo [[96mPERFORM[0m] Apply theme [fd]...
color fd
echo [[96mPERFORM[0m] Set window title [WinPork RTE]...
title WinPork RTE
echo [[92mSUCCESS[0m] Prepared WinPork command center!
echo=
cls
powershell write-host -fore White -back Magenta Welcome to WinPork!
echo Type "nogui" for a list of available WinPork commands.